POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZjVjOWUxZjRiMmEyYzBmMmI4Yzg3NSIsImlhdCI6MTY3NzA3Mzg0M30.FglsIuBjIIk0OPIAljie0fXIXC5coV4_HPE1vPtnaJs

{
    "content": "Single Page Apps use token authorization",
    "important": true
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "User id of the note creator is at the start sent along the request",
    "important": true,
    "userId": "63f5c9e1f4b2a2c0f2b8c875"
}

### invalid post
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}
###
POST https://render-notesapp.onrender.com/api/notes
Content-Type: application/json

{
    "content": "this node from render backend",
    "important": true
}

### invalid post2
POST https://render-notesapp.onrender.com/api/notes
Content-Type: application/json

{
    "content": "14411",
    "important": true
}