POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": 12414314
}
###
POST https://shielded-ridge-97474.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": 12414314
}