POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lucy",
    "number": "124-1431441"
}
### invalid create
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "tt",
    "number": "124-143141341"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "12414314"
}
