POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZjcxODU0ZjFiN2RjZWNiNDdkY2RlYiIsImlhdCI6MTY3NzE1OTcwNiwiZXhwIjoxNjc3MTYzMzA2fQ.6bF0JXlTWjKsOwb9sLlJYQ7Bmr8F-YicwUgYzIEazyU

{
    "title": "the user root's second blog 2",
    "author": "shih hao",
    "url": "www.shihhao.com",
    "likes": 50,
    "userId":"63f71854f1b7dcecb47dcdeb"
}