DELETE http://localhost:3003/api/blogs/63f1b8c2c44ea98319a409f9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZjcxODU0ZjFiN2RjZWNiNDdkY2RlYiIsImlhdCI6MTY3NzU1OTMyMiwiZXhwIjoxNjc3NTYyOTIyfQ._SYC3tGhpZYWl3qfkZ4hh4-zYpaiFkLX4GvP9JTsgeo