DELETE http://localhost:3003/api/blogs/63f9c568f26a499380b0be3a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZjcxODU0ZjFiN2RjZWNiNDdkY2RlYiIsImlhdCI6MTY3OTMwODk5OCwiZXhwIjoxNjc5MzEyNTk4fQ.SFt1AuF5rJE0RBye4OdLJ0b7a9Kt9I5CtwfIiCyLASA